INFO     run_all_uicase.py:test_backStage_authentication.py:215 开始执行脚本test_backStage_authentication:

INFO     run_all_uicase.py:test_backStage_authentication.py:218 开始执行脚本test_backStage_authentication:

INFO     run_all_uicase.py:test_login.py:123 成功进入到密码重置页面
INFO     run_all_uicase.py:test_login.py:130 成功进入到密码修改完成页面
INFO     run_all_uicase.py:test_login.py:123 成功进入到密码重置页面
INFO     run_all_uicase.py:test_login.py:130 成功进入到密码修改完成页面
INFO     run_all_uicase.py:test_backStage_examine.py:73 成功登录后台系统
INFO     run_all_uicase.py:test_backStage_authentication.py:179 企业信息认证
INFO     run_all_uicase.py:test_backStage_authentication.py:196 协议内容确认页面
INFO     run_all_uicase.py:test_backStage_authentication.py:203 二维码认证页面
WARNING  urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED5C350EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/80447e9863d50fb5f2b6b5b680a1a8dd/element
WARNING  urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED5C350190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/80447e9863d50fb5f2b6b5b680a1a8dd/element
WARNING  urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ED5C350F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/80447e9863d50fb5f2b6b5b680a1a8dd/element