INFO     run_all_uicase.py:test_backStage_authentication.py:251 开始执行脚本test_backStage_authentication:

INFO     run_all_uicase.py:test_backStage_authentication.py:254 开始执行脚本test_backStage_authentication:

INFO     run_all_uicase.py:test_login.py:123 成功进入到密码重置页面
INFO     run_all_uicase.py:test_login.py:130 成功进入到密码修改完成页面
INFO     run_all_uicase.py:test_login.py:123 成功进入到密码重置页面
INFO     run_all_uicase.py:test_login.py:130 成功进入到密码修改完成页面
INFO     run_all_uicase.py:test_backStage_examine.py:73 成功登录后台系统
INFO     run_all_uicase.py:test_backStage_authentication.py:214 企业信息认证
INFO     run_all_uicase.py:test_backStage_authentication.py:231 协议内容确认页面
INFO     run_all_uicase.py:test_backStage_authentication.py:238 二维码认证页面
INFO     run_all_uicase.py:test_backStage_examine.py:73 成功登录后台系统
INFO     run_all_uicase.py:test_backStage_authentication.py:214 企业信息认证
INFO     run_all_uicase.py:test_backStage_authentication.py:231 协议内容确认页面
INFO     run_all_uicase.py:test_backStage_authentication.py:238 二维码认证页面
INFO     run_all_uicase.py:test_backStage_authentication.py:41 首页
INFO     run_all_uicase.py:test_backStage_authentication.py:45 产品基本信息
INFO     run_all_uicase.py:test_backStage_authentication.py:121 产品特性
INFO     run_all_uicase.py:test_backStage_authentication.py:136 计分卡
INFO     run_all_uicase.py:test_backStage_authentication.py:143 进件信息
WARNING  urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CD7A48B820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f59e428413b4267d423e728c031a48b3
WARNING  urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CD7A310310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f59e428413b4267d423e728c031a48b3
WARNING  urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CD7A4A1670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f59e428413b4267d423e728c031a48b3