{"name": "test_companyRegister", "status": "broken", "statusDetails": {"message": "redis.exceptions.ResponseError: Command # 9 (GET path:plan:query:customer0kgzxfdcc-0175-756d02c9-8a8a0000-0006) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value", "trace": "@pytest.mark.run(order=1)\n    @allure.severity(\"blocker\")\n    @allure.description(\"ÊµãËØï http://10.10.128.152:10053/user/register ‰∏≠Â∞èÂæÆ‰ºÅ‰∏öÊ≥®ÂÜåÊµÅÁ®ã\")\n    @allure.testcase(\"http://10.10.128.152:10053/user/register\", \"Ê≥®ÂÜå üëá\")\n    def test_companyRegister():\n        if runMode == 'UI':\n            def_name = sys._getframe().f_code.co_name\n            test_Assert = Assert.Assertions(def_name)\n            logger.info(\"ÂºÄÂßãÊâßË°åËÑöÊú¨%s:\\n\", def_name)\n    \n            driver = webdriver.Chrome()\n            driver.maximize_window()\n            driver.get(url_ui_register)\n            # db‰∏≠Ê∏ÖÈô§Â∑≤Ê≥®ÂÜåÁöÑË¥¶Êà∑\n            deleteInforMobile()\n            logger.info(\"ÂØπÂ∑≤Ê≥®ÂÜåÁöÑË¥¶Êà∑ËøõË°åÂà†Èô§Êìç‰Ωú\")\n            sleep(1)\n            waitUntilClick(driver, loginOn.btn_agree_css.value)\n            driver.find_element_by_css_selector(loginOn.btn_agree_css.value).click()\n    \n            waitUntilDisplay(driver, loginOn.input_act_css.value)\n            driver.find_element_by_css_selector(loginOn.input_act_css.value).send_keys(act)\n            driver.find_element_by_css_selector(loginOn.input_pwd_css.value).send_keys(pwd)\n            driver.find_element_by_css_selector(loginOn.input_conPwd_css.value).send_keys(pwd)\n            waitUntilClick(driver, loginOn.btn_phoneCode_css.value)\n            sleep(2)\n            flushDb()\n            driver.find_element_by_css_selector(loginOn.btn_phoneCode_css.value).click()\n    \n            while 1:\n>               message = getPhoneMessage().get(\"regMes\")\n\ntest_flow\\test_Authentication\\test_login.py:79: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\dbLink.py:202: in getPhoneMessage\n    for (k, v) in zip(key_list, pipe.execute()):\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\redis\\client.py:4019: in execute\n    return execute(conn, stack, raise_on_error)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\redis\\client.py:3934: in _execute_transaction\n    self.raise_first_error(commands, response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = Pipeline<ConnectionPool<Connection<host=10.10.128.128,port=6739,db=3>>>\ncommands = [(('GET', b'order:track:0kgvxvvsj-0175-757864e2-8a8a0000-000b'), {}), (('GET', b'order:track:0kgw0dz93-0175-757864e2-8...ct:key::SimpleKey [chengtay-zcd,loan.status]'), {}), (('GET', b'token:05ee021e-aca1-4a5d-874c-555480c46c48'), {}), ...]\nresponse = [b'281192750:3680', b'281192750:3679', b'{\"@class\":\"cn.chengtay.zcd.service.debt.pojo.DebtBO\",\"amount\":[\"java.math.Big...l.Date\",1604540625699],\"expireTime\":[\"java.util.Date\",1604562225699],\"appClaims\":{\"@class\":\"java.util.HashMap\"}}', ...]\n\n    def raise_first_error(self, commands, response):\n        for i, r in enumerate(response):\n            if isinstance(r, ResponseError):\n                self.annotate_exception(r, i + 1, commands[i][0])\n>               raise r\nE               redis.exceptions.ResponseError: Command # 9 (GET path:plan:query:customer0kgzxfdcc-0175-756d02c9-8a8a0000-0006) of pipeline caused error: WRONGTYPE Operation against a key holding the wrong kind of value\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\redis\\client.py:3968: ResponseError"}, "description": "ÊµãËØï http://10.10.128.152:10053/user/register ‰∏≠Â∞èÂæÆ‰ºÅ‰∏öÊ≥®ÂÜåÊµÅÁ®ã", "attachments": [{"name": "log", "source": "01d7b255-feb7-481b-9a02-21e6f44255c7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "601fc64d-0120-4b13-adac-48c71f0aaece-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "41e6e825-f50a-4325-b1ff-bd4470fb7247-attachment.txt", "type": "text/plain"}], "start": 1604540839798, "stop": 1604540853516, "uuid": "41a3aff6-23b7-4039-b288-55b92458c158", "historyId": "dd0646a5c1a798e47c4f25747509dea9", "testCaseId": "1fe2bac8daa9cfa6b5ae5069ce9a9205", "fullName": "test_flow.test_Authentication.test_login#test_companyRegister", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "test_flow.test_Authentication"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "A02-03-00033"}, {"name": "thread", "value": "4576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_flow.test_Authentication.test_login"}], "links": [{"type": "test_case", "url": "http://10.10.128.152:10053/user/register", "name": "Ê≥®ÂÜå üëá"}]}